name: ${project.name}
version: ${project.version}
main: me.sobki.animatedleaves.AnimatedLeaves
author: Sobki
description: Lightweight plugin which adds a particle animation to all leaf blocks.
commands:
    al:
        usage: /al
        description: General help command.
    altoggle:
        usage: /altoggle [--all/<player>]
        description: Toggle AnimatedLeaves effects for the sender (or all/target).
    alreload:
        usage: /alreload
        description: Reload AnimatedLeaves configuration.
permissions:
    animatedleaves.default:
        default: true
        description: Grants access to default permissions.
        children:
            animatedleaves.help: true
            animatedleaves.toggle: true
            animatedleaves.see: true
    animatedleaves.admin:
        default: op
        description: Grants admin access to Animated Leaves.
        children:
            animatedleaves.toggle.other: true
            animatedleaves.toggle.all: true
            animatedleaves.toggle.reload: true
